Update update_alerts.yml

diff --git a/.github/workflows/update_alerts.yml b/.github/workflows/update_alerts.yml
--- a/.github/workflows/update_alerts.yml
+++ b/.github/workflows/update_alerts.yml
@@ -1,8 +1,8 @@
 name: Update Coin Listing Alerts
 
 on:
-  #schedule:
-   # - cron: "*/5 * * * *"  # Runs every 30 minutes
+  # schedule:
+  #   - cron: "*/30 * * * *"  # Uncomment if you want scheduled runs
   workflow_dispatch:  # Allows manual execution from GitHub Actions
 
 permissions:
@@ -29,6 +29,8 @@ jobs:
           SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
           SLACK_CHANNEL_ID: ${{ secrets.SLACK_CHANNEL_ID }}
           GOOGLE_SHEET_API: ${{ secrets.GOOGLE_SHEET_API }}
+          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
+          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
         run: |
           if [ -z "${SLACK_BOT_TOKEN}" ]; then
             echo "SLACK_BOT_TOKEN is missing!"
@@ -42,12 +44,22 @@ jobs:
             echo "GOOGLE_SHEET_API is missing!"
             exit 1
           fi
+          if [ -z "${TELEGRAM_BOT_TOKEN}" ]; then
+            echo "TELEGRAM_BOT_TOKEN is missing!"
+            exit 1
+          fi
+          if [ -z "${TELEGRAM_CHAT_ID}" ]; then
+            echo "TELEGRAM_CHAT_ID is missing!"
+            exit 1
+          fi
 
       - name: Run Python Script
         env:
           SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
           SLACK_CHANNEL_ID: ${{ secrets.SLACK_CHANNEL_ID }}
           GOOGLE_SHEET_API: ${{ secrets.GOOGLE_SHEET_API }}
+          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
+          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
         run: python fetch_alerts.py
 
       - name: Commit & Push Changes
